name: diagnose-gcc
version: 1.0.0
github: "mesabloo/diagnose"
license: BSD3
author: "Ghilain Bergeron"
copyright: "2021-2022 Ghilain Bergeron"
category: "Error Reporting"

dependencies:
- base >= 4.7 && < 5
- diagnose >=3.0.0
- array >= 0.5 && < 0.6
- safe >= 0.3 && < 1
- some >= 1.0 && < 2.0
- transformers >= 0.5 && < 1.0

default-extensions:
- OverloadedStrings
- LambdaCase
- BlockArguments

library:
  source-dirs: src
  exposed-modules:
  - Error.Diagnose.Layout.GCC
  - Error.Diagnose.Layout.GCC.Style

ghc-options:
- -Wall
- -Wextra
# - -Wmissing-local-signatures
# - -Wmonomorphism-restriction

extra-source-files:
- README.md

# This is put at the end for convenience.
synopsis: GCC-like rendering for Diagnose.
 
description: |
  This package simply provides a GCC-like layout for diagnostic rendering.
