name: diagnose
version: 1.2.0
github: "mesabloo/diagnose"
license: BSD3
author: "Mesabloo"
copyright: "2020 Mesabloo"

dependencies:
- base >= 4.7 && < 5
- prettyprinter == 1.7.0
- prettyprinter-ansi-terminal == 1.1.2
- unordered-containers == 0.2.14.0
- hashable == 1.3.0.0
- data-default == 0.7.1.1
- aeson == 1.5.6.0
- bytestring == 0.10.12.0
- text == 1.2.4.1

default-extensions:
- OverloadedStrings
- LambdaCase
- BlockArguments

library:
  source-dirs: src

ghc-options:
- -Wall
- -Wextra
# - -Wmissing-local-signatures
# - -Wmonomorphism-restriction

tests:
  diagnose-tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0
    - -g
    dependencies:
    - diagnose
