name: diagnose-ariadne
version: 1.0.0
github: "mesabloo/diagnose"
license: BSD3
author: "Ghilain Bergeron"
copyright: "2021-2022 Ghilain Bergeron"
category: "Error Reporting"

dependencies:
- base >= 4.7 && < 5
- diagnose >=3.0.0
- array >= 0.5 && < 0.6
- data-default >= 0.7 && < 1
- dlist >= 1.0 && < 1.1
- hashable >= 1.3 && < 2
- prettyprinter >= 1.7.0 && < 2
- prettyprinter-ansi-terminal >= 1.1.0 && < 2
- unordered-containers >= 0.2 && < 0.3
- wcwidth >= 0.0.1 && <1
- text >= 1.0.0.0 && <= 2.0
# ^^^ This is unfortunately required, but as 'prettyprinter' already depends on it, it will already have been fetched
# into the local cache anyway.

default-extensions:
- OverloadedStrings
- LambdaCase
- BlockArguments

library:
  source-dirs: src
  exposed-modules:
  - Error.Diagnose.Layout.Ariadne

ghc-options:
- -Wall
- -Wextra
# - -Wmissing-local-signatures
# - -Wmonomorphism-restriction

extra-source-files: []

tests:
  diagnose-rendering-tests:
    main:                Spec.hs
    source-dirs:         test/rendering
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diagnose
    - diagnose-ariadne
  # diagnose-megaparsec-tests:
  #   main:                  Spec.hs
  #   source-dirs:           test/megaparsec
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - diagnose
  #   - diagnose-ariadne
  #   - text >= 1.2 && < 3
  #   when:
  #    - condition: ! '!(flag(megaparsec-compat))'
  #      buildable: false
  # diagnose-parsec-tests:
  #   main:                  Spec.hs
  #   source-dirs:           test/parsec
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - diagnose
  #   - diagnose-ariadne
  #   - text >= 1.2 && < 3
  #   when:
  #    - condition: ! '!(flag(parsec-compat))'
  #      buildable: false


# This is put at the end for convenience.
synopsis: Ariadne-like rendering for Diagnose.
 
description: |
  This package simply provides an ariadne-like layout for diagnostic rendering.
